apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: nexus3
  name: nexus3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nexus3
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: nexus3
    spec:
      containers:
        - image: klo2k/nexus3
          name: nexus
          ports:
            - containerPort: 8081
          resources: {}
          volumeMounts:
            - mountPath: /nexus-data
              name: nexus-data
      restartPolicy: Always
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-data
status: {}
